name: Build to Dist with Webpack

on:
  push:
    branches: [ new-release ]
  pull_request:
    branches: [ new-release ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist2
        path: |
          dist2        
